/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface AecConfig {
  sampleRate: number
  enableNs?: boolean
}
export declare function createProcessor(cfg: AecConfig): AecHandle
/** 喂 far-end (TTS reference signal),帧必须 10ms */
export declare function processRender(handle: AecHandle, farEndPcm: Float32Array): void
/** 喂 near-end (mic),返回清掉 echo 的 mic */
export declare function processCapture(handle: AecHandle, nearEndPcm: Float32Array): Float32Array
export declare function info(handle: AecHandle): string
export declare class AecHandle { }
