import { MoodParser, XingParser, ThinkTagParser, LynnProgressParser } from "../../core/events.js";
import { createSessionStreamState } from "../session-stream-store.js";

export function createChatTurnState() {
  return {
    thinkTagParser: new ThinkTagParser(),
    progressParser: new LynnProgressParser(),
    moodParser: new MoodParser(),
    xingParser: new XingParser(),
    isThinking: false,
    hasOutput: false,
    hasToolCall: false,
    hasPrefetchToolCall: false,
    hasThinking: false,
    hasError: false,
    titleRequested: false,
    titlePreview: "",
    visibleTextAcc: "",
    rawTextAcc: "",
    pseudoToolSteered: false,
    pseudoToolRecoveryHandled: false,
    pseudoToolCommandRecoveryAttempted: false,
    pseudoToolXmlBlock: null,
    routeIntent: "chat",
    originalPromptText: "",
    effectivePromptText: "",
    hasLocalPrefetchEvidence: false,
    pendingToolRetryAttempted: false,
    internalRetryCounts: {},
    internalRetryPending: false,
    internalRetryInFlight: false,
    internalRetryReason: "",
    successfulToolCount: 0,
    lastSuccessfulTools: [],
    hasFailedTool: false,
    lastFailedTools: [],
    toolFailedFallbackRetryAttempted: false,
    toolFinalizationRetryAttempted: false,
    silentBrainAbortTimer: null,
    turnHardAbortTimer: null,
    toolFinalizationTimer: null,
    deferredTurnEndSafetyTimer: null,
    toolAuthorizationTimer: null,
    toolAuthorizationPollTimer: null,
    returnedTurnFinalizationTimer: null,
    persistedFinalAnswerPollTimer: null,
    persistedAssistantTextBaseline: 0,
    activeStreamToken: null,
    streamSource: null,
    degenerationAbortRequested: false,
    _lastTurnAborted: false,
    progressMarkerCount: 0,
    _turnEndDeferred: false,
    _turnClosed: false,
    lastActivity: Date.now(),
    ...createSessionStreamState(),
  };
}
