import { readVersionInfo } from "./version.js";

export function renderCodeHeadlessHelp(): string {
  const version = readVersionInfo().version || "0.80.0";
  return [
    "Lynn code headless / CLI Fleet",
    "",
    "用途:",
    "  - 给人用: Lynn code",
    "  - 给其他智能体 / CI / GUI Fleet 用: Lynn code -p \"任务\" --json --cwd /repo",
    "",
    "安装(Node.js 20 LTS 或 22 LTS + npm):",
    `  npm install -g --force https://download.merkyorlynn.com/downloads/cli/lynn-cli-${version}.tgz`,
    "",
    "静默调用(处理完直接退出,不进入 TUI):",
    "  Lynn code -p \"review the current diff\" --json --cwd /repo",
    "  Lynn code -p \"fix tests, run the suite, summarize the diff\" \\",
    "    --json --cwd /worktree --approval yolo --sandbox danger-full-access --save-session",
    "",
    "长任务/断点续跑:",
    "  Lynn code -p \"complete the migration until tests pass\" \\",
    "    --json --cwd /worktree --approval yolo --sandbox danger-full-access \\",
    "    --long --max-steps 1000 --save-session",
    "  Lynn code --resume <session.jsonl> -p \"continue\" --json --long",
    "",
    "ultra 模式(实验,opt-in):把大任务拆成原子子任务 → 并行可靠 worker → 对抗式综合:",
    "  Lynn code --ultra -p \"重构 auth 模块并补测试\" \\",
    "    --json --cwd /repo --approval yolo --sandbox danger-full-access",
    "  调参: --ultra-max-subtasks 6  --ultra-concurrency 3  --ultra-verify(每子任务独立 refuter)",
    "  说明: 每个子任务由完整的原子步 + 逐步验证 worker 执行;无法拆分时自动退化为单 worker。",
    "        --save-session 时整轮 ultra 会落一份可 resume / /rewind 的会话(合并各 worker 快照为单检查点)。",
    "",
    "GUI Fleet worker(JSONL 事件流):",
    "  Lynn worker run --brief task.md --worktree /worktree \\",
    "    --jsonl --approval yolo --sandbox danger-full-access",
    "  Lynn worker run --brief task.md --worktree /worktree \\",
    "    --agent custom --agent-command \"your-cli --json\" --jsonl",
    "",
    "规则:",
    "  - 自动化调用只解析 --json / --jsonl,不要解析人类 TUI。",
    "  - 总是传 --cwd 或 --worktree。",
    "  - 交互式 ask 模式会逐次弹出授权;--approval yolo 只用于隔离 git worktree 的零逐条审批。",
    "  - code.tool.ledger 记录每步工具观察,供上层调度和审计。",
    "  - code.task.finished.resumeCommand 存在时,按它继续。",
  ].join("\n");
}
