import { currentLang, t } from "./i18n.js";

export function usage(): string {
  if (currentLang() === "zh") {
    return [
      "Lynn CLI",
      "",
      "用法:",
      "  Lynn version",
      "  Lynn doctor [--offline]",
      "  Lynn brain status | start | stop",
      "  Lynn cache doctor [session.jsonl] [--json]",
      "  Lynn \"问题\"",
      "  cat file.txt | Lynn \"总结这个文件\"",
      "  Lynn - < file.txt",
      "  Lynn -p \"问题\" [--mock-brain] [--json]",
      "  Lynn exec \"任务\" --json [--mock-brain]",
      "  Lynn chat",
      "  Lynn goal \"长任务目标\"",
      "  Lynn --continue",
      "  Lynn --resume <session.jsonl> [继续说明]",
      "  Lynn agents [--json]",
      "  Lynn model [--json]",
      "  Lynn model stepfun --api-key <api-key>",
      "  Lynn model mimo --api-key <api-key>",
      "  Lynn memory",
      "  Lynn memory add <长期事实/偏好/决策>",
      "  Lynn providers [--json]",
      "  Lynn providers presets [--json]",
      "  Lynn providers test [--json]",
      "  Lynn setup",
      "  Lynn byok [set|test|unset|presets]",
      "  Lynn providers set",
      "  Lynn providers set --base-url https://api.example.com/v1 --api-key <api-key> --model model-id",
      "  Lynn providers set --preset mimo --api-key <api-key>",
      "  Lynn providers set --preset stepfun --api-key <api-key>",
      "  Lynn providers unset",
      "  Lynn permissions [--json]",
      "  Lynn permissions set --approval ask|on-failure|yolo --sandbox workspace-write|danger-full-access",
      "  Lynn worker run --brief task.md --worktree path --jsonl --mock",
      "  Lynn worker run --brief task.md --worktree path --jsonl --approval yolo --sandbox danger-full-access",
      "  Lynn code \"review the current diff\"",
      "  Lynn code -p \"review the current diff\" --json",
      "  Lynn code -p \"fix tests\" --json --cwd /repo --approval yolo --sandbox danger-full-access",
      "  Lynn code --resume <session.jsonl> \"继续上次任务\"",
      "  Lynn see screenshot.png [问题]",
      "  Lynn see --images before.png,after.png \"对比这两个界面\"",
      "  Lynn ground screenshot.png \"提交按钮\" --json",
      "  Lynn ui2code mockup.png",
      "  Lynn code --list-tools",
      "  Lynn code --tool read_file --path README.md --json",
      "  Lynn sessions list --json",
      "  Lynn sessions show <path>",
      "  Lynn sessions stats <path>",
      "  Lynn sessions replay <path>",
      "",
      "常用参数:",
      "  --reasoning auto|off|low|medium|high|xhigh",
      "  --show-reasoning auto|always|never",
      "  --no-ink              聊天命令使用旧行式界面",
      "  --brain-url http://127.0.0.1:8790",
      "  --no-route-smoke      doctor 只检查 Brain 健康和 provider route,不发起轻量聊天探测",
      "  --server-url http://127.0.0.1:3000",
      "  --base-url https://api.example.com/v1 --api-key <api-key> --model model-id",
      "  --image path.png 或 --images a.png,b.png",
      "  --approval ask|on-failure|never|yolo",
      "  --sandbox read-only|workspace-write|danger-full-access",
      "  --max-steps 1..300",
      "  --long / --endurance   长任务续航模式,配合断点续跑分段完成",
      "  --save-session --no-save-session --resume <session.jsonl> --data-dir ~/.lynn",
      "  Lynn code 人类交互默认保存断点;JSON/脚本模式需显式 --save-session",
      "  --agent-command \"custom worker command\"",
    ].join("\n");
  }
  return [
    "Lynn CLI",
    "",
    t("help.usage"),
    "  Lynn version",
    "  Lynn doctor [--offline]",
    "  Lynn brain status | start | stop",
    "  Lynn cache doctor [session.jsonl] [--json]",
    "  Lynn \"prompt\"",
    "  cat file.txt | Lynn \"summarize this\"",
    "  Lynn - < file.txt",
    "  Lynn -p \"prompt\" [--mock-brain] [--json]",
    "  Lynn exec \"task\" --json [--mock-brain]",
      "  Lynn chat",
      "  Lynn goal \"long-running objective\"",
      "  Lynn --continue",
    "  Lynn --resume <session.jsonl> [continuation]",
    "  Lynn agents [--json]",
    "  Lynn model [--json]",
    "  Lynn model stepfun --api-key <api-key>",
    "  Lynn model mimo --api-key <api-key>",
    "  Lynn memory",
    "  Lynn memory add <durable fact/preference/decision>",
    "  Lynn providers [--json]",
    "  Lynn providers presets [--json]",
    "  Lynn providers test [--json]",
    "  Lynn setup",
    "  Lynn byok [set|test|unset|presets]",
    "  Lynn providers set",
    "  Lynn providers set --base-url https://api.example.com/v1 --api-key <api-key> --model model-id",
    "  Lynn providers set --preset mimo --api-key <api-key>",
    "  Lynn providers set --preset stepfun --api-key <api-key>",
    "  Lynn providers unset",
    "  Lynn permissions [--json]",
    "  Lynn permissions set --approval ask|on-failure|yolo --sandbox workspace-write|danger-full-access",
      "  Lynn worker run --brief task.md --worktree path --jsonl --mock",
      "  Lynn worker run --brief task.md --worktree path --jsonl --approval yolo --sandbox danger-full-access",
      "  Lynn code \"review the current diff\"",
      "  Lynn code -p \"review the current diff\" --json",
      "  Lynn code -p \"fix tests\" --json --cwd /repo --approval yolo --sandbox danger-full-access",
    "  Lynn code --resume <session.jsonl> \"continue the task\"",
    "  Lynn see screenshot.png [question]",
    "  Lynn see --images before.png,after.png \"compare these screens\"",
    "  Lynn ground screenshot.png \"Submit button\" --json",
    "  Lynn ui2code mockup.png",
    "  Lynn code --list-tools",
    "  Lynn code --tool read_file --path README.md --json",
    "  Lynn sessions list --json",
    "  Lynn sessions show <path>",
    "  Lynn sessions stats <path>",
    "  Lynn sessions replay <path>",
    "",
    t("help.flags"),
    "  --reasoning auto|off|low|medium|high|xhigh",
    "  --show-reasoning auto|always|never",
    "  --no-ink              use the legacy line-mode chat UI",
    "  --brain-url http://127.0.0.1:8790",
    "  --no-route-smoke      doctor checks Brain health/provider route without a chat smoke request",
    "  --server-url http://127.0.0.1:3000",
    "  --base-url https://api.example.com/v1 --api-key <api-key> --model model-id",
    "  --image path.png or --images a.png,b.png",
    "  --approval ask|on-failure|never|yolo",
    "  --sandbox read-only|workspace-write|danger-full-access",
    "  --max-steps 1..300",
    "  --long / --endurance   endurance mode; use checkpoints/resume for longer work",
    "  --save-session --no-save-session --resume <session.jsonl> --data-dir ~/.lynn",
    "  Lynn code human turns autosave checkpoints; JSON/script mode requires --save-session",
    "  --agent-command \"custom worker command\"",
  ].join("\n");
}
